plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.vivalink'
    compileSdk 35 // حدثناه لـ 35 عشان يروح التنبيه

    defaultConfig {
        applicationId "com.example.vivalink"
        minSdk 24
        targetSdk 34 // خليه 34 عشان الاستقرار
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    // ... باقي الكود كما هو ...
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout

    // تحديث نسخة الـ BoM
    implementation platform('com.google.firebase:firebase-bom:34.10.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-analytics'

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}