plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.vivalink'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.vivalink"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout


    implementation platform('com.google.firebase:firebase-bom:34.10.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-analytics'
    // --- إضافة جديدة: Firebase Storage لرفع صور الفحوصات ---
    implementation 'com.google.firebase:firebase-storage'

    // --- إضافة جديدة: مكتبة Glide لعرض الصور وسرعة تحميلها ---
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}